image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup QIIME2 2025.4 with Miniforge/Mamba
    init: |
      # Source bashrc to initialize conda/mamba
      source ~/.bashrc
      
      # Verify mamba installation
      echo "Testing mamba installation..."
      mamba --version
      conda --version
      
      # Create QIIME2 2025.4 environment using mamba (faster than conda)
      echo "Creating QIIME2 2025.4 amplicon environment with mamba..."
      mamba env create \
        --name qiime2-amplicon-2025.4 \
        --file https://raw.githubusercontent.com/qiime2/distributions/refs/heads/dev/2025.4/amplicon/released/qiime2-amplicon-ubuntu-latest-conda.yml
      
      # Activate the environment
      echo "Activating QIIME2 environment..."
      conda activate qiime2-amplicon-2025.4
      
      # Install Krona using mamba (faster)
      echo "Installing Krona with mamba..."
      mamba install -c bioconda krona -y
      
      # Update Krona taxonomy databases
      echo "Updating Krona taxonomy databases..."
      ktUpdateTaxonomy.sh || echo "Warning: Krona taxonomy update may have had issues - this is often due to network timeouts and can be ignored"
      
      # Install q2-krona plugin (may not work with QIIME2 2025.4)
      echo "Installing q2-krona plugin..."
      pip install git+https://github.com/kaanb93/q2-krona.git
      
      # Refresh QIIME2 plugin cache
      echo "Refreshing QIIME2 plugin cache..."
      qiime dev refresh-cache
      
      # Check if q2-krona loaded successfully
      if qiime krona --help >/dev/null 2>&1; then
        echo "✅ q2-krona plugin loaded successfully!"
      else
        echo "⚠️  q2-krona plugin not loaded (compatibility issue with QIIME2 2025.4)"
        echo "📝 Use Krona directly: ktImportText taxonomy.tsv -o plot.html"
      fi
      
      # Add auto-activation to bashrc for future sessions
      echo 'conda activate qiime2-amplicon-2025.4' >> ~/.bashrc
      
      echo ""
      echo "✅ QIIME2 2025.4 setup complete!"
      
    command: |
      # Source bashrc to ensure conda/mamba is available
      source ~/.bashrc
      
      # Fix PATH to prioritize conda over pyenv
      export PATH="/home/gitpod/miniforge3/envs/qiime2-amplicon-2025.4/bin:$PATH"
      
      echo "🔬 QIIME2 2025.4 with Miniforge/Mamba ready!"
      echo ""
      
      # Display version information
      echo "=== 📦 Package Manager Versions ==="
      echo "Conda: $(conda --version)"
      echo "Mamba: $(mamba --version)"
      echo ""
      
      echo "=== 🧬 QIIME2 Information ==="
      qiime --version
      echo ""
      
      echo "=== ℹ️  QIIME2 System Info ==="
      qiime info
      echo ""
      
      echo "=== 🔌 Available QIIME2 Plugins ==="
      qiime --help | grep -A 50 "QIIME 2 help:"
      echo ""
      
      # Verify Krona installation
      echo "=== 🧬 Krona Installation ==="
      which ktImportText || echo "ktImportText not found in PATH"
      ktImportText 2>&1 | head -5 || echo "Krona tools may not be properly installed"
      
      echo ""
      echo "=========================================="
      echo "🎉 Setup complete! QIIME2 2025.4 is ready to use!"
      echo "📚 Documentation: https://library.qiime2.org/quickstart/amplicon"
      echo "💬 Forum: https://forum.qiime2.org/"
      echo ""
      echo "📝 Example commands to try:"
      echo "  qiime --version"
      echo "  qiime info"
      echo "  ktImportText  # Shows Krona usage"
      echo "  mamba list | grep qiime"
      echo "=========================================="

vscode:
  extensions:
    - ms-python.python
    - ms-python.debugpy
    - ms-toolsai.jupyter
    - ms-python.flake8
